        pipeline {
            agent any
            stages {
                stage('Checkout GIT') {
                    steps {
                        echo 'Pulling..'
                        git branch: 'Melek',
                        url : 'https://github.com/MGhassen30798/Devops'
                    }
                }
                stage('MVN Clean') {
                    steps {
                        dir('Spring/tpAchatProject') {
                            sh """mvn clean install"""
                        }
                    }
                }
                stage('MVN Compile') {
                    steps {
                        dir('Spring/tpAchatProject') {
                            sh """mvn compile"""
                        }
                    }
                }
                stage('MVN Test') {
                    steps {
                        dir('Spring/tpAchatProject') {
                            sh """mvn test"""
                        }
                    }
                }
                stage('Sonar'){
                    steps{
                        dir('Spring/tpAchatProject') {
                            sh """mvn -X sonar:sonar  -Dsonar.projectKey=project123 -Dsonar.host.url=http://172.10.0.55:9000 -Dsonar.login=b6f79640b0ac197d18437f50ea41ed53f0f2b5c2"""
                        }
                    }
                }
                stage('Nexus'){
                    steps{
                        dir('Spring/tpAchatProject') {
                            sh """mvn clean package deploy:deploy-file -DgroupId=com.esprit.examen -DartifactId=tpAchatProject -Dversion=1.${env.BUILD_NUMBER} -DgeneratePom=true -Dpackaging=jar -DrepositoryId=deploymentRepo -Durl=http://172.10.0.55:8081/repository/maven-releases/ -Drevision=${env.BUILD_NUMBER} -Dfile=target/tpAchatProject-1.${env.BUILD_NUMBER}.jar"""
                                }
                            }
                        }
                        stage('Pull the file off Nexus') {
                                steps {
                                  dir('Spring/tpAchatProject') {
                                    withCredentials([usernameColonPassword(credentialsId: 'Nexus-Creds', variable: 'NEXUS_CREDENTIALS')]) {
                                      sh script: 'curl -u ${NEXUS_CREDENTIALS} -o ./target/tpachat.jar "http://172.10.0.55:8081/repository/maven-releases/com/esprit/examen/tpAchatProject/1.${env.BUILD_NUMBER}/tpAchatProject-1.${env.BUILD_NUMBER}.jar"'
                                    }
                                  }
                                }
                              }
                    stage('Building Docker Image Angular') {
                           steps {
                               dir('Angular/crud-tuto-front') {
                            sh 'docker build -t mohamedmmc/tpachatfront .'
                       }
                   }
                }
                stage('Building Docker Image') {
                    steps {
                        dir('Spring/tpAchatProject'){
                            sh 'docker build -t mohamedmmc/tpachat .'
                                }
                            }
                        }

                stage('Login to DockerHub') {
                    steps{
                        dir('Spring/tpAchatProject'){
                            sh 'docker login -u mohamedmmc -p azerty123'
                            }
                        }
                    }
                stage('Push to DockerHub') {
                    steps{
                        dir('Spring/tpAchatProject'){
                            sh 'docker push mohamedmmc/tpachat'
                             }
                        }
                    }
                stage('Docker Compose'){
                    steps{
                       dir('Spring/tpAchatProject'){
                            sh 'docker-compose up -d'
                            }
                       }
                    }
                }
            }